language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_install:
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.6.deb && sudo service elasticsearch restart
before_script:
  - composer install
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/,Resources/public/ ./
